[package]
name = "text_to_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

text-to-png = "0.2.0"
image = "0.24.4"
imageproc = "0.23.0"