[package]
name = "wav_noise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
image = "*"
[[bin]]
name = "wav_noise"
path = "wav_noise.rs"
