[package]
name = "enigo_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
crossterm = "0.25.0"
macroquad = "0.3"
serde_json = "1.0.83"